export const AUTHENTICATION = {
  NAME: "auth",
  LOGIN: "login",
  UPDATE_PASSWORD: "update-password",
  OTP: "otp",
  TERMS_AND_CONDITIONS: "terms-and-conditions",
};

export const MODULES = {
  AUTHENTICATION: {
    LOGIN: `/${AUTHENTICATION.NAME}/${AUTHENTICATION.LOGIN}`,
    UPDATEPASSWORD: `/${AUTHENTICATION.NAME}/${AUTHENTICATION.UPDATE_PASSWORD}`,
    OTP: `/${AUTHENTICATION.NAME}/${AUTHENTICATION.OTP}`,
    TERMS_AND_CONDITIONS: `/${AUTHENTICATION.NAME}/${AUTHENTICATION.TERMS_AND_CONDITIONS}`,
  },
};
